### ISSUE TITLE
Building faild!

### ISSUE THREAD

**Issue by YangXiaojun-1024** [lexrus/VPNOn#108]
"Keychain.swift" this class building faild in Xcode 10.1.
Tips:Module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1 compiler: /Users/apple/Desktop/Jun/gitRepository/VPNOn/Carthage/Build/iOS/KeychainAccess.framework/Modules/KeychainAccess.swiftmodule/x86_64.swiftmodule

**Comment by lexrus** [comment]
Just rebuild with Carthage.
