### ISSUE TITLE
可以试试这个 https://github.com/dodois/dosvpn

### ISSUE THREAD

**Issue by dodois** [lexrus/VPNOn#117]

**Comment by nodysOne** [comment]
现在又可以了，就是有时候不稳定



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lex Tang <notifications@github.com&gt;
发送时间: 2020年10月31日 16:05
收件人: lexrus/VPNOn <VPNOn@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lexrus/VPNOn] 可以试试这个 https://github.com/dodois/dosvpn (#117)





 
Closed #117.
