### ISSUE TITLE
Wifi dependent VPN selection 

### ISSUE THREAD

**Issue by m42e** [lexrus/VPNOn#13]
Offer VPN dependent on current WiFi Network Name.

**Comment by lexrus** [comment]
As I know, this can be done with an mobileconfig file. Do you have any idea how to programatically achieve it with NetworkExtension framework or other frameworks?

**Comment by m42e** [comment]
No, I'm sorry, just had the Idea. I'm not familiar with iOS programming.

**Comment by lexrus** [comment]
I did a little research last night, and I confirm it's impossible.
I'm sorry, @m42e.
