### ISSUE TITLE
What's the matter with  "A configuration error occurred.";

### ISSUE THREAD

**Issue by 0x0007de** [lexrus/VPNOn#14]
same configure in Settings(Settings->VPN) was success.

![img_0356](https://cloud.githubusercontent.com/assets/10275908/5610251/8a4b4f08-94ee-11e4-8b34-49f6b4367fed.PNG)

**Comment by 0x1Dx** [comment]
I have this problem too.

**Comment by lexrus** [comment]
I'm sorry I made a mistake: https://github.com/lexrus/VPNOn/commit/8dacb37af334900ca8f0506a56a266dacf689c7d#diff-c265589bf368e1b8e62b942b2407850eL49
It's now fixed.

**Comment by 0x0007de** [comment]
Good job,it works
