### ISSUE TITLE
Do you want save configure when the backitem be pressed in "Edit configure VC"?

### ISSUE THREAD

**Issue by 0x0007de** [lexrus/VPNOn#15]
Always press "Save VPN Configuration" button,and when you back,It didn't alert anything.Then,you lose your configure.

**Comment by lexrus** [comment]
It's the normal logic of most complex setting interfaces of iOS. You may try the native VPN settings.
Yes, we can improve the experience with some friendly prompts. But why Apple can't?

**Comment by 0x0007de** [comment]
Good job,I found a save buttonitem on the right top.
