### ISSUE TITLE
can not compile on Xcode6.1

### ISSUE THREAD

**Issue by alexiscn** [lexrus/VPNOn#20]
I can not compile the project with Xcode6.1

VPN.swift file line 23

if let id = objectID.URIRepresentation().lastPathComponent {

error message
/VPNOn/VPNOnData/VPN.swift:23:50: Bound value in a conditional binding must be of Optional type

**Comment by lexrus** [comment]
As I mentioned before in README.md, it requires Xcode 6.1.1 to compile the project.
`lastPathComponent` is an optional property of type `String?` in latest stable frameworks.
