### ISSUE TITLE
Is possible to switch server on today extension?

### ISSUE THREAD

**Issue by zttt** [lexrus/VPNOn#21]
I tried to access the vpn array from today extension, 
`var vpns = VPNDataManager.sharedManager.allVPN()`

It crashed at first, then I check the TodayWidget target, it stopped crashing, instead, it gave me an empty array. 

Is there any way we can access those data and set the active server from Today Extension?

**Comment by lexrus** [comment]
The CoreData is stored in the container App, it's not directly available in the extension App.
It's a little complicated to share the CoreData, I gonna implement it sooner or later.

**Comment by lexrus** [comment]
@zttt Please checkout the latest source code. I've migrated the CoreData into shared container so that allVPN() is now functional in widget.

**Comment by lexrus** [comment]
In order to display a list or whatever which presents the VPNs, the UI should be carefully designed to match the consistency style of Notification Center. I'd prefer to draw a prototype before coding. Do you have any idea about the UI?

**Comment by zttt** [comment]
Thanks for the update. It works perfect now.

About the UI, I think a collection view is better than a list. Maybe use flags of different country(base on the server IP) to represent VPNs?

**Comment by lexrus** [comment]
Yes, that's what I expected. Furthermore, there should be title labels above or behind each flag in order to indicate different servers in the same country.
First of all, #9 must be done.

**Comment by lexrus** [comment]
![img_1219](https://cloud.githubusercontent.com/assets/219689/6546267/6891f0b2-c5e8-11e4-85f7-8bdcfc131b2d.PNG)

Done.
