### ISSUE TITLE
run crashed:fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by gclsoft** [lexrus/VPNOn#28]
lazy var dataDirectory: NSURL = {
        // The directory the application uses to store the Core Data store file. This code uses a directory named "com.LexTang.VPNOn" in the application's documents Application Support directory.
            return NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier(kAppGroupIdentifier)!// at this line!!!
        }()

**Comment by lexrus** [comment]
Have you turn on the App Groups in capabilities for both target?
