### ISSUE TITLE
Latency test in VPN list

### ISSUE THREAD

**Issue by lexrus** [lexrus/VPNOn#3]

**Comment by 0x0007de** [comment]
cool!

**Comment by lexrus** [comment]
Done.
See https://github.com/lexrus/VPNOn/commit/59a472c2269aa4176b339ece184d40f1019152ba

![screen shot 2015-01-07 at 6 55 51 pm](https://cloud.githubusercontent.com/assets/219689/5644518/2f6459a6-969f-11e4-810b-adc78418b762.png)
