### ISSUE TITLE
VPN On crashes when using vpnon:// link

### ISSUE THREAD

**Issue by nielspeen** [lexrus/VPNOn#34]
When using a link in this format:

vpnon://username:password@server.servers.com/?title=MyServer&alwayson=yes&ikev2=yes&certificate=https://servers.com/ca.pem

Safari will ask to open VPN On correctly and I can see iOS do the switch (the pre-load screenshot of VPN On shows briefly) but the VPN On app then crashes to the home screen immediately.

I've restarted the phone to make sure it's not a low-memory situation, but this did not help.

iOS version is 8.1.3 on iPhone 6 Plus. VPN On is 0.5 from Feb 19th.

**Comment by lexrus** [comment]
Thank you @nielspeen. I'll check it ASAP.

**Comment by lexrus** [comment]
Hi @nielspeen,
It's fixed and may be released in the next release(0.6).
And PEM certificate is not supported yet. It requires a PKCS12 certificate with both the private key and CA certificate inside. I gonna mark this in the next release.

**Comment by nielspeen** [comment]
I still suffer from crashed when the vpnon:// link contains a link to a P12 certificate. The vpnon:// link will correctly launch VPN On and fill out the server information, but as soon as you click Save or enter the Certificate submenu it crashes. 

(In some cases clicking Save does not crash VPN On, but it also does not save the new server.)

**Comment by lexrus** [comment]
@nielspee I'm sorry it does not work as I said in the README. I just deleted the certificate field because it's hard to achieve this function inside the current design.
