### ISSUE TITLE
Connect with CA certificate

### ISSUE THREAD

**Issue by lexrus** [lexrus/VPNOn#35]

**Comment by lexrus** [comment]
After diving into the APIs and a lot of OpenSSL commands, I just realized that iOS 8 requires a PKCS12 certificate with both the private key and the CA certificate. And most VPN providers won't provide private key to customers.

**Comment by nielspeen** [comment]
Is there a reason VPN On needs to install its own IKEv2 profiles? If it could use IKEv2 profiles that are already installed on the device the problem could be avoided.

**Comment by lexrus** [comment]
@nielspeen We can not control them with any public APIs.
