### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by lubieapki** [lexrus/VPNOn#43]
I have a problem
![zrzut ekranu 2015-03-31 o 09 54 18](https://cloud.githubusercontent.com/assets/6787484/6914538/f8fd2fcc-d78b-11e4-8456-7757e1da3fa5.png)

**Comment by lexrus** [comment]
Please ensure AppGroups are configured in every extensions.
![screen shot 2015-03-31 at 3 57 20 pm](https://cloud.githubusercontent.com/assets/219689/6914588/b0d6f61e-d7be-11e4-9b2f-c8f56980b45b.png)
