### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lubieapki** [lexrus/VPNOn#46]
I have a problem
![zrzut ekranu 2015-04-08 o 16 03 37](https://cloud.githubusercontent.com/assets/6787484/7046840/f52eb658-de08-11e4-855d-8a532194a275.png)

**Comment by lexrus** [comment]
I guess you need to clean the project by pressing command + shift + k.
If the error still there, try run the following shell in your Terminal app to clean the entire derived data:
```
rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by lubieapki** [comment]
It doesn't help :(

**Comment by JustinFincher** [comment]
I added `import VPNOnKit` in `VPNManager.swift` then compiled successfully

**Comment by JustinFincher** [comment]
I added `import VPNOnKit` in `VPNManager.swift` then compiled successfully
But I met with other issues so I don't know if that really works....

**Comment by lexrus** [comment]
I just found that the testing target included some files that already embed in the dynamic framework.
It's fixed.
