### ISSUE TITLE
use of undeclared type mmwormhole

### ISSUE THREAD

**Issue by zqpmaster** [lexrus/VPNOn#49]
i change all the capacity and bundle id . but when i run it it has an issue that use of undeclared type mmwormhole

**Comment by lexrus** [comment]
Uh... It's here.
https://github.com/lexrus/VPNOn/blob/develop/VPNOnKit/Vendor/MMWormhole.h

**Comment by zqpmaster** [comment]
工程里是有这个文件。但还是编译不通过。

**Comment by zqpmaster** [comment]
capabilities和bundle_id 我都改好了。

**Comment by lexrus** [comment]
从项目里删掉，再拖进来试试呢？

**Comment by lexrus** [comment]
已修正，请 pull 最新的源码。
