### ISSUE TITLE
ios9 Beta1 下好像无效

### ISSUE THREAD

**Issue by hnboy2005** [lexrus/VPNOn#55]
通知栏里点击了图标没反应

**Comment by lexrus** [comment]
恩，现在 VPN 相关的 API 非常不稳定，尤其是在 iOS 9 下，重启一下手机吧。

**Comment by lexrus** [comment]
重启后可以了吗？

**Comment by hnboy2005** [comment]
更新最新版的IOS9后,能用了 但是还有点小问题 就是通知栏最左侧的图标看不到

[image: Inline image 1]

**Comment by lexrus** [comment]
图片看不见...
