### ISSUE TITLE
协议切换的时候有问题

### ISSUE THREAD

**Issue by hzx1987227** [lexrus/VPNOn#58]
某家服务器同时支持IKEV2和IKEV1协议，

然而groupname 和 secret的设置都是不一样的。

每次切换协议后（当然group和secret都修改了），都需要多连接一次才能成功连上。

经我测试的结果好像是，切换协议后的第一次连接的Profile其实用的还是切换协议前的内容（例如group和secret）

于是导致连接失败。

不知道是不是个案

**Comment by lexrus** [comment]
感谢你报告问题。

可能是有这个问题。建议暂时复制一个 VPN，这样不用每次都改协议。
我正在针对 iOS 9 开发新版，完成后应该不会再有这个问题。

谢谢。

**Comment by hzx1987227** [comment]
感谢回复。

这个问题也存在于协议复制后的列表。

只要选择的服务器协议与上一次连接的协议是不相同的，

就会造成这个问题。(需要连接2次才能正常运作)

当然对实际使用不会有很大障碍 :)

iOS9版本的特性能透露下么？非常愿意参加beta测试

**Comment by lexrus** [comment]
@hzx1987227 在此之前我想再发一个修复这类问题的补丁版，预计 10 月初，到时我在这儿联系你。

**Comment by hzx1987227** [comment]
@lexrus 
好的，如果能出一个修复版本是最好的了，因为我ios8和iso9一起用的。

ios9下也有类似问题，ios9下第一次安装配置文件的时候和ios8有点不一样，

会导致连接按钮失效，重启程序有可以正常工作。

而TODAY插件第一次安装配置文件后也无法正常工作的样子，

重启系统后可以正常工作。

希望以上信息能帮到你

**Comment by lexrus** [comment]
@hzx1987227 感谢你的反馈。iOS 9 下我测试得不全面，这周会花时间好好测一下。

**Comment by iammecn** [comment]
是有这样的问题，我是在Appstore里下载的版本，不知道最近否有更新修复这个问题？

**Comment by lexrus** [comment]
我现在加了一个 0.1 秒的延迟貌似是解决了这个问题了，今晚提交审核。

**Comment by hzx1987227** [comment]
感谢针对本问题的修复。

现在发现一个不怎么影响使用（？）的BUG

也是发生在切换协议的时候。

连接IKEV2的服务器后再连接IPSEC的服务器

会导致状态栏VPN图标的消失，但是VPNON显示已连接，实际检测也是已经连上VPN服务器。

而且WIFI的图标也会消失，不知道是不是个例。

**Comment by lexrus** [comment]
我升级到 iOS 9 之后也发现了这个问题，暂时还不知道是什么原因。
