### ISSUE TITLE
想问一下按需连接怎么用？

### ISSUE THREAD

**Issue by iammecn** [lexrus/VPNOn#64]
你好！
我在app store里购买了这个软件，已经在依赖域名那里增加了相关的网址，但通过safari里访问 相关网址，发现没有自动拨vpn,请问这个功能具体怎么使用？
![c2a3f606f6256e521197cfb7286a3bb1](https://cloud.githubusercontent.com/assets/3390459/10637611/332b601c-7839-11e5-8072-9339b926ff29.png)

**Comment by lexrus** [comment]
设置完后请开关一次当前 VPN 以更新设置。

**Comment by iammecn** [comment]
果然有效了，谢谢
但保持在线的选项应该不适用于IPSec
请确认下

**Comment by lexrus** [comment]
按需连接的问题会在 #57 里修正。

保持在线其实是一个叫 disconnectOnSleep 的属性，我查了一下苹果的文档，对于 IPSec 协议，也是有支持：
https://developer.apple.com/library/prerelease/ios/documentation/NetworkExtension/Reference/NEVPNProtocolClassRef/index.html#//apple_ref/occ/instp/NEVPNProtocol/disconnectOnSleep
