### ISSUE TITLE
VPN On widget: Flags icon not updated and button disapear

### ISSUE THREAD

**Issue by atika** [lexrus/VPNOn#68]
Hi,
I just bought VPN On on Mac App Store and I see two little things:
- Flags doesn"t appear. On telize.com a message said that after November 15th the api will shut down.
- The little switch to change to switch view disapear when cliqued.

Tested on iPhone 5.

**Comment by lexrus** [comment]
Thank you for the notice. I'm looking for a local GeoIP DB which can be bundled in my App so that it's not necessary to request any server.

**Comment by atika** [comment]
You're welcome
There are no other services for this, even if we have to create an api key.
I use GeoIP Lite on my server, but a compiled version: http://dev.maxmind.com/geoip/legacy/geolite/
And I just found this: http://lite.ip2location.com/main

**Comment by lexrus** [comment]
Hi @atika 
I made a wrapper over libmaxminddb and open-sourced it as a separate repo.
https://github.com/lexrus/MMDB-Swift
I gonna integrate it into VPN On ASAP.
