### ISSUE TITLE
能用Url Scheme关闭VPN吗？

### ISSUE THREAD

**Issue by dvder** [lexrus/VPNOn#71]
能不能增加Url Scheme，来关闭打开的VPNON打开的VPN呢。然后不管用Url Scheme打开VPN还是关闭VPN，都可以自此之后自动退出软件呢，类似Cisco AnyConnect。谢谢～

**Comment by lexrus** [comment]
谢谢你的建议，下一版再加一个断开的功能。

**Comment by dvder** [comment]
谢谢，Lexrus~
