### ISSUE TITLE
关于用Url Scheme打开VPN

### ISSUE THREAD

**Issue by dvder** [lexrus/VPNOn#72]
我发现如果VPNON在没有运行的时候，使用vpnon://VPNTitle/?connect只是打开VPNON，但不会链接指定的VPN，需要再次使用vpnon://VPNTitle/?connect，才能打开指定的VPN，这个可以修正一下吗，谢谢～

**Comment by lexrus** [comment]
抱歉这么久才回复你，我明天看一下这个问题。

**Comment by lexrus** [comment]
已修复，今晚提交审核。
