### ISSUE TITLE
编译出错 

### ISSUE THREAD

**Issue by strong6619** [lexrus/VPNOn#77]
![bcf8c972-0bd5-457d-9e16-2421728a9a2c](https://cloud.githubusercontent.com/assets/778414/14083413/36881fde-f548-11e5-9140-b692a10c2577.png)
![bcf8c972-0bd5-457d-9e16-2421728a9a2c](https://cloud.githubusercontent.com/assets/778414/14083413/36881fde-f548-11e5-9140-b692a10c2577.png)
这个应该如何决绝呢

**Comment by lexrus** [comment]
试试最新的版本？
