### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by RylynnLai** [lexrus/VPNOn#79]
fatal error: unexpectedly found nil while unwrapping an Optional value

遇到这个错误，不知道其他人有没遇到

**Comment by lexrus** [comment]
你好，请问一下具体是错在哪一块儿？

**Comment by RylynnLai** [comment]
![2016-04-24 10 45 20](https://cloud.githubusercontent.com/assets/14285525/14773306/14988fa0-0adb-11e6-93a6-831d283ed18b.png)
很高兴得到你的回复，我是在编译完一运行就会出错

**Comment by lexrus** [comment]
看样子是在旧版数据库更新到新版时出错的，你试一下删了 App 重新编译呢？

**Comment by RylynnLai** [comment]
![2016-04-25 1 00 45](https://cloud.githubusercontent.com/assets/14285525/14774210/21667aa2-0ae6-11e6-86cb-a7ea8ac035f6.png)

你好，我把app删除，xcode里面clean后，一样的结果，用模拟器编译运行后会定位到这个位置出错。

另外，配置证书的时候，我更改bundle ID为com.LexTang.VPNOn.lai，后来尝试搜索项目里的com.LexTang.VPNOn替换为com.LexTang.VPNOn.lai。发觉没效果。。。

**Comment by lexrus** [comment]
你没有建好 App Group 吧？

**Comment by RylynnLai** [comment]
果然是App Group我没配置好,我把你之前的App Group改了.

很感谢你耐心的解答!!
我仍有很多东西需要学习

**Comment by lexrus** [comment]
谢谢。
