### ISSUE TITLE
在 ios 9.3.1 系统上面，无法从 today widget 开启vpn，点击widget 开关按钮无反应。

### ISSUE THREAD

**Issue by liaozibo** [lexrus/VPNOn#80]
如题。xcode7.3 在 ios 9.3.1 编译安装通过，VPN不能从 widget 进行开关，widget 点击无效
貌似后来，自己又莫名好了。诡异。抱歉打扰。

**Comment by lexrus** [comment]
重启一下 iPhone 就好。
