### ISSUE TITLE
What's the condition of VPNOn auto running?

### ISSUE THREAD

**Issue by chinsyo** [lexrus/VPNOn#82]
I have downloaded the project and dive into the source code, your code is clean and pretty.  Due to the swift version, I can't run the project directly so I bought the application in `App Store`.

During the time using the app, I found it always auto running in background, of course I give it the access.

I have two questions below.

First, what's the difference between the `vpn` appear in the top-left corner of the screen or top-right corner of the screen.

Second, why the application auto running when I playing `Hearth Stone` and how to config the auto running for a domain?

Look forward to your reply.

**Comment by lexrus** [comment]
Thank you for your feedback.
1. No difference. The VPN tag decides where it appear according to available space of the status bar.
2. Uh... How did you config the on-demand list?
