### ISSUE TITLE
What about downloading an url for configuring VPNs?

### ISSUE THREAD

**Issue by erickguan** [lexrus/VPNOn#83]
For example, I am using VPNCloud so that I would like to manage all the servers at once.

**Comment by nikolay-dementiev** [comment]
Hello.

Tell more in detail about your problem
And, if possible, give a few screenshots

**Comment by lexrus** [comment]
Yes, you mean a .mobileconfig file to provisioning all the VPN servers automatically.
Same as: https://github.com/lexrus/VPNOn/issues/60

**Comment by msalenazi** [comment]
How do I add server configurations in VIN on iPhone 7 iOS 10.2.1 knowing I have purchased the application

**Comment by lexrus** [comment]
@msalenazi Please do not post redundant content to multiple issues. This may disturb other users who have no responsibility for your question. You can contact me via lexrus@gmail.com
It's not pretty clear what you mean. Could you be more specific on your problem?
