### ISSUE TITLE
iOS 10 compatibility issue

### ISSUE THREAD

**Issue by puxxustc** [lexrus/VPNOn#85]
System: iPhone SE with iOS 10.0(14A5345a)
Version: 0.9.6 (from App Store)

The widget is blank, shown as below. Besides, after uninstall and reinstall, VPN profile in system preference can not be deleted and the connect button does not work.

1: widget is blank.
![image](https://cloud.githubusercontent.com/assets/4092563/17853404/d77050be-689e-11e6-9365-6b1ae136373f.png)

2: connect button is on, but VPN is not connected.
![image](https://cloud.githubusercontent.com/assets/4092563/17853541/a31d5068-689f-11e6-96be-26dbff40ba28.png)

**Comment by lexrus** [comment]
Thank you for your feedback.
It's not iOS 10 compatible yet. I gonna fix it these days.

**Comment by puxxustc** [comment]
Hi, thanks for your work. After updated to v0.9.7, everything works well except that the old VPN profile can not be deleted, shown as follows. I'd appreciate if you could help to solve this little defect.

![image](https://cloud.githubusercontent.com/assets/4092563/18501305/04ed575e-7a82-11e6-8abb-4d6e4905dc77.png)

**Comment by lexrus** [comment]
I’m afraid I can’t. I gonna report this bug to Apple.

Here is a redeem code of VPN On which you can send to your friend.

http://tokn.co/rd7a6u99

**Comment by puxxustc** [comment]
Thank you.
