### ISSUE TITLE
不支持 Remote ID，因此无法使用云梯 VPN。

### ISSUE THREAD

**Issue by Moskize91** [lexrus/VPNOn#86]
以下是云梯客服的反馈：

> 由于 VPN On 还不支持配置 Remote Id，所以需要等其更新后，才能支持云梯。你也可以联系 VPN On 的开发者，反馈 Remote Id 的支持需求。

希望能支持，让云梯用户也可以用 VPNOn。

**Comment by liaozibo** [comment]
你这个和 vpnon 无关，是需要云梯支持 ikev2 协议才行。

**Comment by lexrus** [comment]
@Moskize91 下一版试着加上。

**Comment by lexrus** [comment]
试了一下，的确是 Remote ID 必填且不能有错，不然连不上。

**Comment by Moskize91** [comment]
@liaozibo 云梯应该是号称支持 ikev2 的，比如：

> p4.jp1.dancedidu.com  正常  IKEv2   电信良好。联通优秀。移动良好。

这个域名应该是支持的。

**Comment by Moskize91** [comment]
@lexrus 非常感谢，我现在已经安装了 VPNOn 了，因为用云梯暂时用不了。期待你的更新。:)

**Comment by liaozibo** [comment]
不对啊，我看 ftq.link 这家的 vpn 就是可以用 vpnon 的 ikev2 的，不需要 Remote ID。
@Moskize91 为啥？

**Comment by lexrus** [comment]
最新的 develop 分支的代码已经支持某梯，亲测可用。准备在 0.9.8 中提交，请楼主耐心等待。

**Comment by Moskize91** [comment]
@lexrus 非常感谢
