### ISSUE TITLE
无法连接云梯IKEv2 VPN服务器

### ISSUE THREAD

**Issue by shoujs** [lexrus/VPNOn#90]
iOS 10.1 系统
今天刚刚购买的，第一次使用。
从系统的vpn开关可以连上服务器
同样的服务器通过VPNOn就无法连接，无论在wifi或者4g网络下，都连接失败了。

**Comment by lexrus** [comment]
你好，麻烦装一下云梯的 mobileconfig，里面有个 CA 证书连接时需要用到。

**Comment by shoujs** [comment]
你好，
我在下载VPNOn之前已经安装过云梯的mobileconfig了。
是不是需要重新安装一次证书文件？

**Comment by shoujs** [comment]
![img_1848](https://cloud.githubusercontent.com/assets/815432/19846540/30d69ba0-9f7b-11e6-83b4-8b3df4a4502c.PNG)
![img_1847](https://cloud.githubusercontent.com/assets/815432/19846542/362c3dee-9f7b-11e6-9578-16f1a8fe221a.PNG)
![img_1846](https://cloud.githubusercontent.com/assets/815432/19846544/3a2826c4-9f7b-11e6-8c19-4ab2d09e7521.PNG)

**Comment by lexrus** [comment]
Remote-ID 设置了吗？

**Comment by shoujs** [comment]
填了和服务器同样的地址
![default](https://cloud.githubusercontent.com/assets/815432/19846834/656eb396-9f7d-11e6-8207-633f08aad8c2.png)

**Comment by lexrus** [comment]
填 server.vpncloudca.com 试试。

**Comment by shoujs** [comment]
可以连上了！谢谢！
