### ISSUE TITLE
Why the URLs of the VPNs you provided are unvalid? Are you sure they are valid? Thanks!

### ISSUE THREAD

**Issue by zhihuihuashen** [lexrus/VPNOn#93]
where is the wrong?

**Comment by zhihuihuashen** [comment]
![img_2135](https://user-images.githubusercontent.com/16166867/28201532-163160d0-68a4-11e7-9f62-5967f1cdbd25.PNG)

**Comment by lexrus** [comment]
我没有提供 VPN，202.96.209.* 是上海电信。

**Comment by zhihuihuashen** [comment]
@lexrus 那其他的，比如google，apple的呢？也是不行的

**Comment by zhihuihuashen** [comment]
@lexrus 有没有可以测试的，谢谢！

**Comment by lexrus** [comment]
你看的是 README 里的例子，本工具不提供服务。

**Comment by zhihuihuashen** [comment]
哦，好的，谢谢
