### ISSUE TITLE
 line 2: /usr/local/bin/carthage: No such file or directory

### ISSUE THREAD

**Issue by oneLeaf2012** [lexrus/VPNOn#96]
VPNOn.build/Debug-iphoneos/VPNOn.build/Script-D78C5EAE1D716D2F00E54F6C.sh: line 2: /usr/local/bin/carthage: No such file or directory

**Comment by oneLeaf2012** [comment]
error: unexpectedly found nil while unwrapping an Optional value

**Comment by XGCoder** [comment]
请问你这个问题解决了吗 ? 我现在这边也是出现这样的 "line 2: /usr/local/bin/carthage: No such file or directory"  的问题

**Comment by lexrus** [comment]
`brew install carthage`

**Comment by XGCoder** [comment]
Thank you, I'm trying now

**Comment by XGCoder** [comment]
Thank you, I have successfully building and run to the device. !!!
